### PR TITLE
implement #12 add-xua-x-service-provider-support

### PR DESCRIPTION
**Pull request by walcovanloon**
* use CXF wss4j integration to enable SAML token validation
* add base configuration for SAML token validation

(integration test on the way)

### CODE REVIEW

**Comment by Thopap** [comment]
@walcovanloon:

Your proposal looks quiet good, i was not aware that the CXF wss4j is that easy to integrate :-) I have already played around with a local token and it was working as expected.

I was not able to send my suggestion to your branch, so i have placed some suggestions on a temporary branch:
https://github.com/oehf/xds-registry-to-fhir/commit/fafb1e8e0cf31de0fe12c44d5a07a7c5e1704906
That basically contain the following remarks:
* adding properties as example
* remove version from pom, since cxf bom is already imported
* Use Smart initiazation instead of the interceptor "action" flag to avoid a little bit more overhead if xua is disabled

Please takeover the remarks you agree to, i will remove my branch afterwards.
If you can contribute a small integration test in addition, this would be perfect to finish this improvement.

**Comment by walcovanloon** [comment]
> @walcovanloon:
> 
> Your proposal looks quiet good, i was not aware that the CXF wss4j is that easy to integrate :-) I have already played around with a local token and it was working as expected.
> 
> I was not able to send my suggestion to your branch, so i have placed some suggestions on a temporary branch: [fafb1e8](https://github.com/oehf/xds-registry-to-fhir/commit/fafb1e8e0cf31de0fe12c44d5a07a7c5e1704906) That basically contain the following remarks:
> 
> * adding properties as example
> * remove version from pom, since cxf bom is already imported
> * Use Smart initiazation instead of the interceptor "action" flag to avoid a little bit more overhead if xua is disabled
> 
> Please takeover the remarks you agree to, i will remove my branch afterwards. If you can contribute a small integration test in addition, this would be perfect to finish this improvement.

I could easily pull in your branch and continue on it. Perfect, liked the improvements :)

**Comment by Thopap** [comment]
* I have merged the PR and fixed the Port conflict by setting the dirtiesContext configuration. Now the IT tests run fine in commandline.
* The "ClassNotFound" issue was also interesting. The root cause here was also, that an outdated spring version was used at all. If have fixed the imports here.
* The XUA Processor was already enabled as port of https://github.com/oehf/xds-registry-to-fhir/commit/389cdb2d9cc54bfc785f5b11344c7db78155c5be

I will now update the documentation of the new properties in https://github.com/oehf/xds-registry-to-fhir/wiki/Deployment-&-Configuration#application-configuration-properties

**Comment by walcovanloon** [comment]
> Thanks a lot for this contributation. I have merged the PR and perform some small adaptions:
> 
> * Fixed the Port conflict by setting the dirtiesContext configuration. Now the IT tests run fine in commandline.
> * The "ClassNotFound" issue was also interesting. The root cause here was also, that an outdated spring version was used at all (was not intended). If have fixed the imports here so it now get the correct most recent spring-core version from spring-boot (6.1.13).
> * IPF Xua Support is basically just the ATNA part of XUA which was already enabled as part of [389cdb2](https://github.com/oehf/xds-registry-to-fhir/commit/389cdb2d9cc54bfc785f5b11344c7db78155c5be)
> 
> I will now update the documentation of the new properties in https://github.com/oehf/xds-registry-to-fhir/wiki/Deployment-&-Configuration#application-configuration-properties

Amazing! Thanks a lot for the improvements and getting it in so quickly :-)

**Pull request merged**
